definitions:
  model.Event:
    properties:
      ack_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      event_type:
        type: string
      id:
        type: string
      payload:
        type: string
      priority:
        type: integer
    type: object
  model.IdResponse:
    properties:
      id:
        type: string
    type: object
  model.StateResponse:
    properties:
      description:
        type: string
      state:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/events:
    get:
      consumes:
      - '*/*'
      description: retrieves all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Event'
            type: array
      summary: retrieve all events
      tags:
      - Event
    post:
      consumes:
      - '*/*'
      description: creates an event
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.IdResponse'
      summary: create an event
      tags:
      - Event
  /api/v1/events/:event_id:
    delete:
      consumes:
      - '*/*'
      description: delete an event by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: body
      summary: delete an event
      tags:
      - Event
    get:
      consumes:
      - '*/*'
      description: retrieves an event by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Event'
      summary: retrieve an event
      tags:
      - Event
  /api/v1/events/:event_id/publish-state:
    get:
      consumes:
      - '*/*'
      description: get publish state of event with asynchronous publish type by event
        id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StateResponse'
      summary: get publish state of event
      tags:
      - Event
  /api/v1/events/publish-state/:ack_id:
    get:
      consumes:
      - '*/*'
      description: get publish state of event with asynchronous publish type by ack
        id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StateResponse'
      summary: get publish state of event
      tags:
      - Event
swagger: "2.0"
