name: Docker Image CI

on:
  push:
    branches: [ dev-ci ]
  pull_request:
    branches: [ dev-ci ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy Dockerfile to root
      run: cp ./build/package/Dockerfile .
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Etefagh:$(date +%s)
